(()=>{"use strict";
const $=s=>document.querySelector(s);
const canvas=$("#sceneCanvas"),ctx=canvas.getContext("2d");
let state=null;
const order=["wake","breakfast","commute","arrival","locker","homeroom","quiz","hallway","english","lunch","cafeteria","project","rumor","last","after","home"];
const statMeta=[["energy","Energy","energy"],["stress","Stress","stress"],["grades","Grades","grades"],["friends","Friends","friends"],["integrity","Integrity","integrity"],["money","Money","money"],["character","Character","character"]];
const baseStats={energy:72,stress:24,grades:70,friends:55,integrity:76,money:12,character:70};
const scenes={
wake:{time:"6:45 AM",loc:"Bedroom",view:"bedroom",tag:"MORNING",title:"Alarm.",text:"Bus comes soon.",choices:[["Get up.",{energy:-1,stress:-2,character:2},"You move fast.","breakfast","Self-control early helps later.","Proverbs 25:28"],["Snooze.",{energy:3,stress:5},"More sleep. Less time.","breakfast"],["Check phone.",{energy:-2,stress:7,character:-2},"You lose time.","breakfast","Not every alert deserves first place.","Psalm 5:3"]]},
breakfast:{time:"7:00 AM",loc:"Kitchen",view:"kitchen",tag:"CHOICE",title:"Breakfast?",text:"Eat or rush?",choices:[["Eat fast.",{energy:8,stress:-2,character:1},"Good fuel.","commute",null,null,"Water Bottle"],["Skip it.",{energy:-7,stress:2},"You save time.","commute"],["Take cash.",{money:3,energy:1},"Maybe buy food later.","commute"]]},
commute:{time:"7:18 AM",loc:"Outside",view:"bus",tag:"BUS",title:"Bus at corner.",text:"It is leaving.",random:true,choices:[["Run.",{energy:-5,stress:2,character:1},"You make a run for it.","arrival"],["Get a ride.",{stress:4,character:-1},"You ask for help.","arrival"],["Fake sick.",{stress:-5,grades:-7,integrity:-8,character:-6},"You dodge school.","arrival","Avoiding duty costs later.","Colossians 3:23"]]},
arrival:{time:"7:48 AM",loc:"School",view:"school",tag:"ARRIVAL",title:"Crowded hall.",text:"You need your notes.",choices:[["Go locker.",{energy:-2,stress:-4,character:2},"You get organized.","locker"],["Find friends.",{friends:5,stress:-2,energy:-1},"You get a boost.","locker"],["Check chat.",{grades:2,stress:3,energy:-1},"Quiz is today.","locker"]]},
locker:{time:"7:55 AM",loc:"Locker 214",view:"locker",tag:"MINI GAME",title:"Locker code?",text:"You blank on it.",choices:[["Memory game.",null,null,null,null,null,null,"locker"],["Ask for help.",{stress:3,energy:-2,character:1},"It takes longer.","homeroom","Wise people ask for help.","Proverbs 12:15"],["Skip notes.",{grades:-5,stress:4},"You gamble.","homeroom"]]},
homeroom:{time:"8:08 AM",loc:"Homeroom",view:"class",tag:"NEWS",title:"Quiz moved up.",text:"Math quiz is now.",choices:[["Review.",{grades:6,stress:-1,energy:-2,character:1},"You prep fast.","quiz"],["Ask friend.",{grades:3,friends:1,stress:1},"You get one tip.","quiz"],["Wing it.",{grades:-5,stress:1},"Bold choice.","quiz"]]},
quiz:{time:"8:20 AM",loc:"Math",view:"class",tag:"QUIZ",title:"Three questions.",text:"Do your best.",choices:[["Start quiz.",null,null,null,null,null,null,"quiz"]]},
hallway:{time:"9:05 AM",loc:"Hall",view:"hall",tag:"HALLWAY",title:"New student lost.",text:"They look confused.",choices:[["Walk with them.",{friends:6,stress:2,energy:-2,character:8,integrity:4},"You help them.","english","Love notices people.","Philippians 2:4",null,null,"YOU SAW THEM"],["Point the way.",{friends:2,character:3},"Quick help.","english"],["Keep going.",{character:-4},"You move on.","english","Good left undone still matters.","James 4:17"]]},
english:{time:"10:15 AM",loc:"English",view:"class",tag:"TEST",title:"“Let me copy.”",text:"A friend wants your work.",choices:[["Let them.",{friends:5,integrity:-13,character:-9,grades:-2},"They copy it.","lunch","Helping wrong is not true help.","Proverbs 10:9"],["Say no. Help later.",{friends:2,energy:-3,integrity:9,character:8},"Kind and firm.","lunch","Truth and love fit together.","Ephesians 4:15",null,null,"STEADY COMPASS"],["Refuse harshly.",{integrity:6,friends:-6,character:-1},"Right answer, rough tone.","lunch","Grace matters too.","Colossians 4:6"]]},
lunch:{time:"11:42 AM",loc:"Cafeteria",view:"lunch",tag:"LUNCH",title:"Where sit?",text:"Friends or new kid?",random:true,choices:[["Friends.",{friends:5,stress:-4,energy:3},"Safe pick.","cafeteria"],["Invite new kid.",{friends:7,character:9,integrity:3,stress:2},"You make room.","cafeteria","Belonging starts with room made.","Romans 15:7",null,null,"MAKE ROOM"],["Do homework.",{grades:6,energy:2,friends:-2,stress:1},"You work through lunch.","cafeteria"]]},
cafeteria:{time:"12:03 PM",loc:"Cafeteria",view:"lunch",tag:"MOMENT",title:"Tray drops.",text:"People laugh.",choices:[["Laugh too.",{friends:3,character:-9,integrity:-7},"The table laughs.","project","Crowds can reward wrong.","Romans 12:2"],["Stay quiet.",{character:-2},"You say nothing.","project"],["Speak up.",{friends:-1,stress:4,character:11,integrity:8},"You defend them.","project","Courage speaks.","Proverbs 31:8",null,null,"COURAGE > COMFORT"],["Help them.",{energy:-2,friends:2,character:10,integrity:5},"You step in.","project",null,null,null,null,"COURAGE > COMFORT"]]},
project:{time:"1:10 PM",loc:"Science",view:"class",tag:"GROUP",title:"Teammate does nothing.",text:"Your group needs help.",choices:[["Do it all.",{grades:7,energy:-9,stress:8,friends:1},"Grade improves.","rumor","Serving is good. Enabling isn't always.","Galatians 6:5"],["Give a task.",{grades:6,stress:2,friends:3,character:7},"You lead clearly.","rumor","Healthy leadership is honest.","Matthew 18:15",null,null,"TEAM CAPTAIN"],["Tell teacher.",{grades:3,friends:-5,stress:-2,character:1},"Problem reported.","rumor"]]},
rumor:{time:"2:05 PM",loc:"Hall",view:"hall",tag:"PHONE",title:"Rumor text.",text:"“Send this to everybody.”",choices:[["Forward.",{friends:3,integrity:-12,character:-10,stress:4},"Rumor grows.","last","Small gossip is still gossip.","Proverbs 16:28"],["Delete.",{integrity:5,character:3,stress:-1},"It stops with you.","last"],["Question it.",{integrity:9,character:7,stress:3},"You slow it down.","last","Wisdom checks first.","Proverbs 18:13",null,null,"RUMOR BREAKER"],["Check on them.",{friends:5,character:10,energy:-2,integrity:6},"You choose the person.","last","People matter more than gossip.","Luke 6:31",null,null,"RUMOR BREAKER"]]},
last:{time:"2:40 PM",loc:"History",view:"class",tag:"LAST PERIOD",title:"Worn out.",text:"One more graded task.",choices:[["Do the work.",{energy:-6,grades:7,stress:2,character:5},"You finish strong.","after","Faithfulness is often ordinary.","Luke 16:10"],["Copy answers.",{grades:2,integrity:-11,character:-8,stress:-2},"Easy now. Costly later.","after"],["Do half.",{energy:-2,grades:3,stress:-1,character:2},"You do what you can.","after"]]},
after:{time:"3:18 PM",loc:"Front Hall",view:"school",tag:"AFTER SCHOOL",title:"Teacher needs help.",text:"Ride leaves soon.",choices:[["Stay and help.",{energy:-5,character:8,friends:2,stress:2},"You serve anyway.","home","Service matters when unseen.","Mark 10:45"],["Head out.",{energy:2,stress:-2},"You go home.","home"],["Ignore it.",{integrity:-3,character:-3},"You act like you didn't hear.","home"]]},
home:{time:"4:07 PM",loc:"Home",view:"home",tag:"HOME",title:"“How was school?”",text:"Hide or be real?",choices:[["Say “fine.”",{energy:3,stress:1,friends:-1},"Short answer.","END"],["Tell truth.",{stress:-7,character:6,integrity:5,friends:2},"You open up.","END","Honesty opens room for help.","Galatians 6:2",null,null,"REAL TALK"],["Polished version.",{integrity:-5,character:-3,stress:-1},"Sounds better than true.","END"]]}
};
const randomEvents=[{title:"Spill!",text:"Drink spills on your notes.",choices:[["Snap back.",{stress:5,friends:-4,character:-3},"It becomes a fight."],["Clean it.",{energy:-2,stress:1,character:4},"You stay calm."],["Joke.",{stress:-3,friends:3,character:3},"Tension drops."]]},{title:"$5 on floor.",text:"No one sees it.",choices:[["Keep it.",{money:5,integrity:-6,character:-4},"You pocket it."],["Turn it in.",{integrity:8,character:6},"You do right.",null,null,null,null,null,"FOUND, NOT MINE"],["Ask around.",{friends:2,integrity:6,character:5},"You find the owner."]]},{title:"Friend upset.",text:"They say, “I'm fine.”",choices:[["Ask again.",{friends:6,energy:-2,character:6},"They feel seen."],["Check later.",{friends:3,character:3},"You remember."],["Move on.",{character:-2},"You leave it alone."]]}];
const quizBank=[["8 × 7 = ?",["54","56","64"],1],["Water freezes at?",["0°C","10°C","100°C"],0],["Prime number?",["21","29","33"],1],["Their is right in?",["Their late.","Their project won.","Put it over their."],1],["Thesis statement?",["Main point","Ends paragraph","Lists sources"],0]];
function fresh(){const stats={...baseStats},type=$("#typeInput").value;if(type==="scholar"){stats.grades+=9;stats.friends-=3;stats.stress+=4}if(type==="social"){stats.friends+=10;stats.grades-=3;stats.energy+=2}if(type==="resilient"){stats.energy+=8;stats.stress-=8;stats.character+=3}return{name:($("#nameInput").value.trim()||"Alex").slice(0,18),grade:$("#gradeInput").value,difficulty:$("#difficultyInput").value,faith:$("#faithInput").checked,stats,inventory:["Phone","Backpack","Chromebook"],achievements:[],history:[],scene:"wake",pending:null,feedback:null,lesson:null,quizScore:0,quizIndex:0,quizQuestions:[]}}
function start(){state=fresh();$("#start").classList.add("hidden");$("#ending").classList.add("hidden");$("#game").classList.remove("hidden");$("#playerName").textContent=state.name;$("#playerGrade").textContent=state.grade;render()}
function render(){const s=scenes[state.scene];$("#hudTime").textContent=s.time;$("#hudLoc").textContent=s.loc;$("#sceneKicker").textContent=s.tag;$("#sceneTitle").textContent=s.title;$("#sceneText").innerHTML=`<p>${s.text}</p>`;$("#mini").classList.add("hidden");$("#mini").innerHTML="";showFeedback();buttons(s.choices);side();progress();draw(s.view)}
function showFeedback(){const f=$("#feedback"),l=$("#lesson");if(state.feedback){f.classList.remove("hidden");f.innerHTML=`<strong>RESULT:</strong> ${state.feedback}`;state.feedback=null}else f.classList.add("hidden");if(state.lesson&&state.faith){l.classList.remove("hidden");l.innerHTML=`<strong>CHARACTER:</strong> ${state.lesson[0]}<div class="muted">${state.lesson[1]}</div>`;state.lesson=null}else{l.classList.add("hidden");if(!state.faith)state.lesson=null}}
function buttons(list){const w=$("#choices");w.innerHTML="";list.forEach((c,i)=>{const b=document.createElement("button");b.textContent=`${i+1}. ${c[0]}`;b.onclick=()=>choose(c);w.appendChild(b)})}
function choose(c){if(c[7]==="locker"){lockerGame();return}if(c[7]==="quiz"){quizGame();return}if(c[1])effects(c[1]);if(c[6]&&!state.inventory.includes(c[6]))state.inventory.push(c[6]);if(c[8])badge(c[8]);state.feedback=c[2]||"Choice made.";if(c[4])state.lesson=[c[4],c[5]||""];const time=scenes[state.scene]?.time||"";state.history.unshift(`${time} — ${c[2]||c[0]}`);state.history=state.history.slice(0,10);achievements();if(c[3]==="END"){finish();return}route(c[3],scenes[state.scene]?.random)}
function route(next,random){if(random&&Math.random()<chance()){state.pending=next;randomEvent();return}state.scene=next;render()}
function chance(){return state.difficulty==="easy"?.18:state.difficulty==="hard"?.55:.34}
function randomEvent(){const e=randomEvents[Math.floor(Math.random()*randomEvents.length)];$("#sceneKicker").textContent="RANDOM";$("#sceneTitle").textContent=e.title;$("#sceneText").innerHTML=`<p>${e.text}</p>`;$("#feedback").classList.add("hidden");$("#lesson").classList.add("hidden");draw("random");buttons(e.choices.map(c=>{const x=[...c];x[3]=state.pending;return x}))}
function effects(e){for(const[k,v]of Object.entries(e)){state.stats[k]=k==="money"?Math.max(0,state.stats[k]+v):Math.max(0,Math.min(100,Math.round(state.stats[k]+v)))}}
function side(){$("#stats").innerHTML=statMeta.map(([k,l,cls])=>{const v=state.stats[k],w=k==="money"?Math.min(100,v*5):v;return `<div class="stat"><div class="statline"><span>${l}</span><strong>${k==="money"?"$":""}${v}</strong></div><div class="bar"><div class="fill ${cls}" style="width:${w}%"></div></div></div>`}).join("");$("#inventory").innerHTML=state.inventory.map(x=>`<span class="chip">${x}</span>`).join("");$("#achievements").innerHTML=state.achievements.length?state.achievements.map(x=>`<span class="chip">★ ${x}</span>`).join(""):`<span class="muted">None yet.</span>`;$("#history").innerHTML=state.history.length?state.history.map(x=>`<div>${x}</div>`).join(""):`<div>Nothing yet.</div>`;$("#lensBtn").textContent=`LENS: ${state.faith?"ON":"OFF"}`}
function progress(){const i=Math.max(0,order.indexOf(state.scene));$("#prog").style.width=`${Math.round(i/(order.length-1)*100)}%`}
function badge(a){if(a&&!state.achievements.includes(a))state.achievements.push(a)}
function achievements(){if(state.stats.integrity>=90)badge("STEADY COMPASS");if(state.stats.character>=90)badge("CHARACTER BUILDER");if(state.stats.friends>=85)badge("PEOPLE PERSON")}
function lockerGame(){$("#choices").innerHTML="";const m=$("#mini");m.classList.remove("hidden");const combo=[1,2,3].map(()=>Math.floor(Math.random()*9)+1).join("-");state.combo=combo;m.innerHTML=`<div class="tag">LOCKER GAME</div><p>Remember:</p><div id="codeShow" class="score">${combo}</div><button id="hideCode">HIDE</button><div id="codeForm" class="hidden"><input id="codeInput" placeholder="1-2-3"><div class="row"><button id="tryCode">TRY</button><button id="skipCode">SKIP</button></div></div>`;$("#hideCode").onclick=()=>{$("#codeShow").textContent="???";$("#hideCode").classList.add("hidden");$("#codeForm").classList.remove("hidden")};$("#tryCode").onclick=()=>{if($("#codeInput").value.trim()===combo){effects({stress:-5,character:3,energy:1});state.feedback="You remembered it.";badge("LOCKER LEGEND")}else{effects({stress:5,energy:-2});state.feedback=`Wrong. It was ${combo}.`}state.scene="homeroom";render()};$("#skipCode").onclick=()=>{effects({stress:2,energy:-2});state.feedback="You ask for help.";state.scene="homeroom";render()}}
function quizGame(){$("#choices").innerHTML="";state.quizQuestions=[...quizBank].sort(()=>Math.random()-.5).slice(0,3);state.quizIndex=0;state.quizScore=0;quizQuestion()}
function quizQuestion(){const m=$("#mini");m.classList.remove("hidden");const q=state.quizQuestions[state.quizIndex];m.innerHTML=`<div class="tag">QUIZ ${state.quizIndex+1}/3</div><p><strong>${q[0]}</strong></p><div id="quizChoices" class="menu"></div>`;q[1].forEach((a,i)=>{const b=document.createElement("button");b.textContent=a;b.onclick=()=>quizAnswer(i===q[2]);$("#quizChoices").appendChild(b)})}
function quizAnswer(ok){if(ok)state.quizScore++;state.quizIndex++;if(state.quizIndex<3){quizQuestion();return}let e,txt;if(state.quizScore===3){e={grades:10,stress:-4,character:2};txt="Perfect quiz.";badge("QUIZ ACE")}else if(state.quizScore===2){e={grades:6,stress:-1};txt="Solid quiz."}else if(state.quizScore===1){e={grades:-1,stress:4};txt="Rough quiz."}else{e={grades:-6,stress:8};txt="Bad quiz."}effects(e);state.feedback=txt;state.history.unshift(`8:20 AM — Quiz ${state.quizScore}/3`);state.scene="hallway";render()}
function finish(){$("#game").classList.add("hidden");$("#ending").classList.remove("hidden");const s=state.stats;const score=Math.max(0,Math.min(100,Math.round(s.energy*.08+(100-s.stress)*.14+s.grades*.18+s.friends*.13+s.integrity*.21+s.character*.26)));let t,x;if(s.stress>=82||s.energy<=18){t="BURNOUT WARNING";x="You made it, but the day drained you."}else if(s.integrity>=88&&s.character>=88){t="QUIET LEADER";x="You chose courage, honesty, and care."}else if(s.grades>=88){t="SCHOLAR";x="You stayed focused and strong in class."}else if(s.friends>=82&&s.character>=78){t="CONNECTOR";x="You helped people belong."}else if(s.character>=80){t="STEADY FRIEND";x="You were consistently solid."}else{t="SURVIVOR";x="You made it through Monday."}$("#endingScore").textContent=score;$("#endingTitle").textContent=t;$("#endingText").textContent=x;$("#endingStats").textContent=statMeta.map(([k,l])=>`${l}: ${k==="money"?"$":""}${s[k]}`).join(" • ");$("#endingReflection").textContent=state.faith?"Whatever you do, do it all for the glory of God. — 1 Corinthians 10:31":"Your choices built your path.";try{localStorage.removeItem("schoolTrailSave")}catch{}}
function save(){if(!state){alert("Start a game first.");return}try{localStorage.setItem("schoolTrailSave",JSON.stringify(state));alert("Game saved.")}catch{alert("Save unavailable.")}}
function load(){try{const r=localStorage.getItem("schoolTrailSave");if(!r){alert("No saved game.");return}state=JSON.parse(r);$("#start").classList.add("hidden");$("#ending").classList.add("hidden");$("#game").classList.remove("hidden");$("#playerName").textContent=state.name;$("#playerGrade").textContent=state.grade;render()}catch{alert("Could not load save.")}}
function reset(){state=null;$("#game").classList.add("hidden");$("#ending").classList.add("hidden");$("#start").classList.remove("hidden")}
function draw(type){const c=ctx;c.imageSmoothingEnabled=false;c.clearRect(0,0,320,180);const r=(x,y,w,h,col)=>{c.fillStyle=col;c.fillRect(x,y,w,h)},stick=(x,y,col="#222")=>{r(x,y,8,16,col);r(x+2,y-8,4,8,col);r(x+2,y+16,2,8,col);r(x+5,y+16,2,8,col)},sky=()=>{r(0,0,320,120,"#89b7e0");r(0,120,320,60,"#6eaa5b")};const school=()=>{sky();r(80,55,160,70,"#c9b07b");r(70,45,180,12,"#7e5a2d");r(145,85,30,40,"#5e3d22");r(0,130,320,50,"#777")};const bedroom=()=>{r(0,0,320,180,"#9a765f");r(0,120,320,60,"#6d4d39");r(30,60,100,50,"#4466aa");r(35,65,90,40,"#6d8fd9");r(200,55,55,55,"#7a5b38")};const kitchen=()=>{r(0,0,320,180,"#d2c2a1");r(0,130,320,50,"#987654");r(25,55,90,65,"#5f8f5f");r(150,80,100,30,"#7c5b38")};const bus=()=>{sky();r(0,130,320,50,"#737373");r(90,75,120,40,"#f1c24b");r(95,80,25,20,"#9ed7ff");r(125,80,25,20,"#9ed7ff");r(155,80,25,20,"#9ed7ff");stick(230,100)};const locker=()=>{r(0,0,320,180,"#7b8e9e");for(let i=0;i<5;i++){r(20+i*55,25,42,120,"#516b7a");r(24+i*55,30,34,110,"#628090")}stick(260,110)};const cls=()=>{r(0,0,320,180,"#cdb88a");r(20,25,90,40,"#2d4d2d");r(130,95,45,20,"#7b5734");r(190,95,45,20,"#7b5734");stick(45,95);stick(220,120);stick(265,110)};const hall=()=>{r(0,0,320,180,"#b2bcc6");r(20,20,60,120,"#6a7a86");r(100,20,60,120,"#6a7a86");r(180,20,60,120,"#6a7a86");stick(270,110);stick(245,108,"#5a2d6a")};const lunch=()=>{r(0,0,320,180,"#c9d7e1");r(40,60,95,18,"#7b5734");r(185,60,95,18,"#7b5734");r(50,92,95,18,"#7b5734");stick(70,44);stick(225,44,"#5a2d6a")};const home=()=>{r(0,0,320,180,"#d9c59f");r(0,130,320,50,"#845f3c");r(45,55,85,60,"#6d8fd9");r(160,70,100,40,"#91663f");stick(200,95);stick(235,95,"#5a2d6a")};const random=()=>{r(0,0,320,180,"#2a2418");for(let y=0;y<6;y++)for(let x=0;x<10;x++)r(20+x*28,20+y*22,12,12,(x+y)%2?"#7f6a3e":"#e2bb55")};({bedroom,kitchen,bus,school,locker,class:cls,hall,lunch,home,random}[type]||school)()}
$("#startBtn").onclick=start;$("#saveBtn").onclick=save;$("#loadBtn").onclick=load;$("#restartBtn").onclick=reset;$("#againBtn").onclick=reset;$("#lensBtn").onclick=()=>{state.faith=!state.faith;side();$("#lesson").classList.add("hidden")};
})();